name : "Hello Actions"
description : "Greet Someone"
author : "vetriselvan1187@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"
 
runs:
  using: "Docker"
  image: "Dockerfile"
  
branding:
  icon: "mic"
  color: "purple"
  
